lesson-15
olennikovandrey/if-js pull request #19
Opened 2021-11-05 09:24 UTC by olennikovandrey

I'll remake some position, it's just a workable copy of project

2021-11-07 19:17 UTC, olennikovandrey commented
I know, there is some bugs, but i still thinking hot fix it

2021-11-08 01:12 UTC, Dronom requested changes
the search button reloads the page and does not count the number of adults and children

2021-11-08 01:12 UTC, Dronom commented on TripHouse/styles/style.css
> +*/
?

2021-11-08 01:12 UTC, Dronom commented on TripHouse/js/main.js
> +};*/
?

2021-11-08 01:12 UTC, Dronom commented on TripHouse/js/main.js
> +    childAgeSelect10.classList.add('hide');
think about how to make it so that it does not depend on the quantity and it worked for both 10 and 100

2021-11-08 01:12 UTC, Dronom commented on TripHouse/js/main.js
> +    let strURL = `https://fe-student-api.herokuapp.com/api/hotels?search=${citySearchInput.value}&adults=${counterAdult.value}&children=${childAgeSelect1.value},${childAgeSelect2.value},${childAgeSel
1. const
2. ${childAgeSelect2.value},${childAgeSelect3.value},${childAgeSelect4.value},${childAgeSel.... it is bad. Make the variables that you just insert into the query string. Better yet, create a function that will return the result to you in the desired form.

2021-11-15 10:29 UTC, olennikovandrey commented on TripHouse/js/main.js
> +    childAgeSelect10.classList.add('hide');
fixed!

2021-11-15 10:30 UTC, olennikovandrey commented on TripHouse/styles/style.css
> +*/
fixed

2021-11-15 10:30 UTC, olennikovandrey commented on TripHouse/js/main.js
> +};*/
fixed

2021-11-15 10:30 UTC, olennikovandrey commented on TripHouse/js/main.js
> +    let strURL = `https://fe-student-api.herokuapp.com/api/hotels?search=${citySearchInput.value}&adults=${counterAdult.value}&children=${childAgeSelect1.value},${childAgeSelect2.value},${childAgeSel
fixed

2021-11-17 23:42 UTC, Dronom reviewed
if your new request you get an empty array, you should clear previous houses
![image](https://user-images.githubusercontent.com/20189313/142299794-f69c78fe-1754-45da-ac41-3a90bcfc3fe0.png)

2021-11-17 23:43 UTC, Dronom reviewed
everything else is good

2021-11-17 23:43 UTC, Dronom commented on TripHouse/js/main.js
> +}
![image](https://user-images.githubusercontent.com/20189313/142300012-bdeb0e5e-cf38-49fb-8b3c-6eb66a9188f8.png)

2022-03-21 08:20 UTC, merged